### ISSUE TITLE
Issue with Kotlin and inheritance

### ISSUE THREAD

**Issue by PVergneau** [quarkiverse/quarkus-bucket4j#154]
Hello there, 

I'm having trouble using the extension whenever my resource is inheriting from another class.  

On this simple example (hopefully enough to reproduce, if not let me know) with inheritance and some base class elements used in the child:

```
package mypackage

import io.quarkiverse.bucket4j.runtime.RateLimited
import jakarta.enterprise.context.ApplicationScoped
import jakarta.ws.rs.*


open class RTBaseResource {
    var counter: Int = 0
}


@RateLimited(bucket = "grp-xp")
@ApplicationScoped
@Path("/xp")
class RTResource : RTBaseResource() {

    @GET
    @Path("/a")
    fun getA() {
        counter++
        return
    }
}

```

at runtime, whenever the endpoint `/xp/a` is called, i'm having this exception:

```
java.lang.NullPointerException: Cannot invoke "io.quarkiverse.bucket4j.runtime.BucketPod.consumeAndReturnNanoWaitTime()" because the return value of "io.quarkiverse.bucket4j.runtime.BucketPodStorage.getBucketPod(java.lang.reflect.Method)" is null
        at io.quarkiverse.bucket4j.runtime.RateLimitedInterceptor.around(RateLimitedInterceptor.java:27)
        at io.quarkiverse.bucket4j.runtime.RateLimitedInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at mypackage.RTResource_Subclass.getCounter(Unknown Source)
        at mypackage.RTResource.getA(RTResource.kt:43)
        at mypackage.RTResource_Subclass.getA$$superforward(Unknown Source)
        at mypackage.RTResource_Subclass$$function$$2.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkiverse.bucket4j.runtime.RateLimitedInterceptor.around(RateLimitedInterceptor.java:29)
        at io.quarkiverse.bucket4j.runtime.RateLimitedInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at mypackage.RTResource_Subclass.getA(Unknown Source)
        at mypackage.RTResource_ClientProxy.getA(Unknown Source)
        at mypackage.RTResource$quarkusrestinvoker$getA_6a82ef51d10b35cc109cac84dee60e14703759dd.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

With no inheritance, the extension is working as expected.

Am i missing some gradle configuration to change the way the classes are compiled and integrated in the build ?

Thanks in advance.

**Comment by lu1tr0n** [comment]
Hi @rmanibus,

I was able to reproduce this: a method inherited from a parent class was failing instead of running. I opened #183 that fixes it, so inherited methods now run normally, and added a test covering the case.

Thanks!
